### ISSUE TITLE
Compile the plugin from a empty start?

### ISSUE THREAD

**Issue by kuohsuanlo** [DRE2N/DungeonsXL#357] opened 2018-02-09 21:08 UTC
I've tried to compile this plugin but it took hours but in vain. I first using buildtools to build craftbukkit required from 1.9 to 1.12
And execute the .bat file. However it stop at dxl-abstract. And 1.10 craftbukkit seems not compile properly, the MVN install process just stop and say it can't load the 1.10 jar file.

Is there any proper steps proved that is able to compile this plugin for user or any one interested in forking ?

**Comment by Sataniel98** [comment] 2018-02-09 23:01
Does building the 0.16 branch - which contains all of the most recent changes - work?

**Comment by kuohsuanlo** [comment] 2018-02-10 04:11
I will try it right now.

**Comment by kuohsuanlo** [comment] 2018-02-10 04:23
executing build.bat under `D:\workspace\DungeonsXL-0.16`
https://paste.ofcode.org/PRCcFzFxprde3MR3C8aDMN
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.
5.1:compile (default-compile) on project dungeonsxl: Fatal error compiling: tool
s.jar not found: C:\Program Files\Java\jre1.8.0_151\..\lib\tools.jar -> [Help 1]`

I guess it as the BuildTools.jar from spigot, so I copy and rename it to `C:\Program Files (x86)\Java\lib`.
But still having the same problem.

**Comment by kuohsuanlo** [comment] 2018-02-10 04:25
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.
5.1:compile (default-compile) on project dungeonsxl: Fatal error compiling: tool
s.jar not found: C:\Program Files\Java\jre1.8.0_151\..\lib\tools.jar -> [Help 1]

What is tool.jar actually?

**Comment by kuohsuanlo** [comment] 2018-02-10 04:28
And if I import the project into Eclipse and run maven install, it shows
https://paste.ofcode.org/r2PDKbKGZveyF4uhTZT66b
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:compile (default-compile) on project dungeonsxl: Compilation failure
[ERROR] error: error reading C:\Users\LogoCat\.m2\repository\io\github\dre2n\caliburn\0.3\caliburn-0.3.jar; error in opening zip file`

Is there any built .jar file for the project?

I try todownload and build caliburnAPI, but still not working.
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.
5.1:compile (default-compile) on project caliburn: Fatal error compiling: tools.
jar not found: C:\Program Files\Java\jre1.8.0_151\..\lib\tools.jar -> [Help 1]`

**Comment by kuohsuanlo** [comment] 2018-02-10 04:38
As for `DRECommons`
Its quite the same as the master branch's problem.

https://paste.ofcode.org/xxm6uBgatDqHNdfpRdqJkk
`[INFO] DRECommons ......................................... SUCCESS [  0.250 s]`
`[INFO] commons-abstract ................................... FAILURE [01:33 min]`
`[INFO] commons-glowstone .................................. SKIPPED`

`[ERROR] Failed to execute goal on project commons-abstract: Could not resolve de
pendencies for project io.github.dre2n:commons-abstract:jar:3.1.4: Could not tra
nsfer artifact org.mcstats.bukkit:metrics:jar:R8-20160303.160206-10 from/to Plug
in Metrics (http://repo.mcstats.org/content/repositories/public): Failed to tran
sfer file: http://repo.mcstats.org/content/repositories/public/org/mcstats/bukki
t/metrics/R8-SNAPSHOT/metrics-R8-20160303.160206-10.jar. Return code is: 522 , R
easonPhrase:Origin Connection Time-out. -> [Help 1]`

**Comment by kuohsuanlo** [comment] 2018-02-10 04:41
If there is a machine independent "compiling from zero" best practice provided, I would be so grateful. 
Or more convenient for both of us, perhaps you could provide a built jar? 
It would be helpful since we don't need to build our own. (DREPlugin.jar , caliburn-0.3.jar) 

 I just want to solve the Griefprevention incompatible issue for the community but still stuck in the library compilation issue. Quite frustrating. 

And by the way, inside the DREcommon pom.xml, some of the links inside the building process are gone  too. 
`http://repo.mcstats.org/content/repositories/public` doesn't contain
`http://repo.mcstats.org/content/repositories/public/org/bukkit/craftbukkit/1.12-pre2-SNAPSHOT/craftbukkit-1.12-pre2-SNAPSHOT.jar`

**Comment by kuohsuanlo** [comment] 2018-02-10 06:17
I finally managed to build a working one. I've removed glowstone, 1.8R123 and some dependency I don't need.

**Comment by kuohsuanlo** [comment] 2018-02-10 06:47
In short, I did not do much. I just add
`	@EventHandler(ignoreCancelled = true, priority = EventPriority.HIGHEST)` in every single listener insdie GlobalProtectionListener, to make sure DXL is handling the event at last and considering other plugin's cancellation behavior. @Sataniel98 

This could just solve the problem. Hope you update it soon. 
GlobalProtectionListener.java https://paste.ofcode.org/BJ6fVhwiUWHmnvJkrLduJt

**Comment by Sataniel98** [comment] 2018-02-11 22:41
All dependencies should be fetched from the repo. Thus, the API jar (org.spigotmc:spigot-api) should be enough since DXL doesn't require any NMS as of 0.16. I cleaned my local repo and tried it again. Fetching Caliburn didn't work for me, neither. It turned out I misspelled something in the repo, but it's fixed now and works fine. I believe the missing "tools.jar" thing might be this: https://stackoverflow.com/questions/25185634/fatal-error-compiling-tools-jar-not-found

Thank you for making me aware that the issue is caused by wrong event priorities. Since the issue appears in dungeons as well if destroying blocks is allowed, changing it in the GlobalProtectionListener won't fix everything. Other affected methods should be inside DWorldListener. I'm having a look at it right now.

**Comment by kuohsuanlo** [comment] 2018-02-12 09:33
Just a gentle reminder : 

@EventHandler(ignoreCancelled = true, priority = EventPriority.HIGHEST)

ignoreCancelled = true ==> if event is cancelled. return immediately.
EventPriority.HIGHEST ==> execute this listener LAST!

Kind of opposite to what it is named. 😆 
FYI

**Comment by Sataniel98** [comment] 2018-02-14 15:37
Sorry, for the record: Did you notice I did anything wrong? ^^

By the way, I've merged the 0.16 branch into the master branch. DXL now uses the latest version of my Commons library and I've started to move some stuff to a new Maven repo, so please tell me if you experience any new issues.

**Closed as completed** 2018-04-24 20:56 UTC
Labels: QUESTION
