### ISSUE TITLE
Please read my issue.

### ISSUE THREAD

**Issue by Ecilpse** [DRE2N/DungeonsXL#217] opened 2017-03-04 14:13 UTC
I am resubmitting this issue because the previous one was not responeded eventhough I bumped the issure.
Please check the issue via the link below:
https://github.com/DRE2N/DungeonsXL/issues/215

**Comment by Sataniel98** [comment] 2017-03-04 19:54
I did reply to it a few times. I am aware of your issue. Things might take a bit time to get reproduced and eventually fixed now and again depending on university stuff and other Bukkit projects, but I never forget about issues as long as they are still open due to the way I'm working on them. Bumps are not necessary. Excuse me if I failed to communicate this :)

**Closed as completed** 2017-03-07 23:30 UTC
