### ISSUE TITLE
Plugin not working after updating to 1.16.3

### ISSUE THREAD

**Issue by doctorblanket** [DRE2N/DungeonsXL#890] opened 2020-09-11 23:19 UTC
The plugin was working just fine when we were running on 1.15.2, but now that we've updated to 1.16.3, the commands don't work (none of them) and the console is being spammed with the following error: https://pastebin.com/mEJnd6fb

**Comment by Sataniel98** [comment] 2020-09-11 23:24
Duplicate of #889

**Closed as completed by Sataniel98** 2020-09-11 23:24 UTC
Labels: DUPLICATE
