### ISSUE TITLE
Sign Breaking Bug

### ISSUE THREAD

**Issue by Masterofjumping** [DRE2N/DungeonsXL#326] opened 2017-10-15 02:23 UTC
With both the latest dev build and latest stable builds of DungeonsXL, player's are able to break world guard protected signs in any world.

Essentially the world guard break deny message still appears stating "you cannot break the block here" but the signs will pop off the wall or floor. It does not happen to every sign but appears to affect some randomly. 

I've isolated DungeonsXL as the issue as the problem resolves itself when the plugin is disabled and then started again when I tried different versions of DXL. This is happening outside dungeons.

I'm not sure how or why DXL is affecting signs outside of dungeons and allowing players to bypass world guard protections for them but it is quite an annoying bug.

Hope you can help, thanks

**Comment by Sataniel98** [comment] 2017-10-15 13:13
Duplicate of #215

**Closed as completed** 2017-10-15 13:14 UTC
Labels: DUPLICATE
