### ISSUE TITLE
Cannot keep inventory - Rules added

### ISSUE THREAD

**Issue by Levelxminecraft** [DRE2N/DungeonsXL#646] opened 2019-08-10 12:01 UTC
I have created a config.yml within the map directory:
keepInventoryOnEnter: true
keepInventoryOnFinish: true
keepInventoryOnEscape: true

^ With these values

Yet people get reset items on entry

Any assistance?

**Comment by Sataniel98** [comment] 2019-08-19 22:44
Duplicate of #647

**Closed as completed by Sataniel98** 2019-08-19 22:44 UTC
Labels: DUPLICATE
