### ISSUE TITLE
 Unable to summon MOB

### ISSUE THREAD

**Issue by qw2456549** [DRE2N/DungeonsXL#485] opened 2018-10-28 14:28 UTC
[mythicmobs]
mobID
1,1
D 10
Unable to summon MOBS
[MM] to

**Comment by Sataniel98** [comment] 2018-10-28 15:35
Duplicate of #484, @neox91120 gave the correct answer. MythicMobs signs have been removed about two years ago, external provider plugins are now used through a parameter in the third line.

**Closed as completed by Sataniel98** 2018-10-28 15:35 UTC
Labels: DUPLICATE
