### ISSUE TITLE
DXL_Game_X cannot be deleted and more and more

### ISSUE THREAD

**Issue by BearLeonLight** [DRE2N/DungeonsXL#622] opened 2019-07-26 15:42 UTC
I use [/mv import DXL_Game_0 normal] to load, then 1.[/mv delete DXL_Game_0]2.[/mvconfirm] can delete the map normally.
Can you add Multiverse-Core support to remove the dungeon map.

**Comment by Sataniel98** [comment] 2019-07-26 16:28
No, DXL instances aren't supposed to be imported into Multiverse, and that they aren't removed isn't intended design but a duplicate of #506

**Closed as completed by Sataniel98** 2019-07-26 16:28 UTC
Labels: DUPLICATE, WON'T FIX

**Comment by BearLeonLight** [comment] 2019-07-27 00:31
So what should I do?
