### ISSUE TITLE
[Question] 0.16 release

### ISSUE THREAD

**Issue by Tiplish** [DRE2N/DungeonsXL#375] opened 2018-04-26 15:07 UTC
Hello,

I'm waiting a stable 0.16 version before upgrading DXL on my server but I've seen some add in the last dev build that i really want to see on my server. So i would know if you think that 0.16 will be released in less than 2 months? 

It's not to put pressure on you, it's just to decide if i upgrad with a dev build or if i could wait the 0.16 official release :)

Thanks

**Comment by Sataniel98** [comment] 2018-04-26 21:24
Hi,
the new features that are planned for 0.16 are all done now except that the new version of my item library which is a dependency for DungeonsXL isn't finished. That doesn't mean that much, because as you probably know, 0.16 has been a bugfix update to begin with. But it's hard to guess how long these bugfixes will take. Plus, I have yet to have a look at the issues that are listed as "Not confirmed possible bugfixes" [in the to do list](https://github.com/DRE2N/DungeonsXL/wiki/changelog). Of course, I can't advise to use unstable software in a production environment, but I wouldn't call 0.15.x stable either. I'm actually thinking about releasing 0.16 as soon as the item library is done even if not _everything_ on the to do list is fixed. The gap between the documentation in the wiki and the feature span of 0.15.x is just getting confusingly big, and I'd like to get it released before 1.13. That being said, a new release within the next month is probable, but not promised, and some bugfixes might get shifted to a 0.16.x release.

**Comment by Tiplish** [comment] 2018-04-27 07:08
Ok thanks for the information :)

**Comment by Sataniel98** [comment] 2018-05-02 00:25
Update: I'd like to get the [major wave update](../issues/383) included in 0.16. I don't think it makes much sense to duct tape the old system when it obviously needs to be overhauled. Besides that, DXL seems to progress well. The new update to the [Caliburn project](https://github.com/DRE2N/CaliburnAPI/wiki) has been committed yesterday. I'm positive the new DXL update will be released relatively soon.

**Comment by Tiplish** [comment] 2018-05-02 07:06
I will share it to my team and i will give you a feedback as soon as possible.

**Comment by Sataniel98** [comment] 2018-05-31 18:43
FINALLY

**Closed as completed by Sataniel98** 2018-05-31 18:43 UTC
Labels: QUESTION
