### ISSUE TITLE
Stuck in group

### ISSUE THREAD

**Issue by apc274003** [DRE2N/DungeonsXL#767] opened 2020-04-18 02:43 UTC
(Please follow this template, as doing so saves both you and me a lot of time.
Issues that don't follow the template may be closed.)

(A clear and concise description of what the bug is, e.g.:
Every time my mob signs spawn pigs, they turn green and fly away.)

Initial lives set to 1, player dies, they are sent to spawn, and still stuck in the group,sometimes player gets stuck in dungeon and the dungeon is frozen

(List steps to reproduce, e.g.:
1. Create a new dungeon with /dxl create
2. Place [ready] sign, [mob]/pig/0,1/D5 sign
3. Leave edit mode with /dxl leave
4. Test with /dxl play
5. Trigger ready sign and get close to the location of the pig spawn sign)

**Expected behavior**

Player dies, player leaves group, and is teleported to the portal they entered from

(A clear and concise description of what you expected to happen, e.g.:
I wanted the pigs to turn blue and dig mole-like tunnels instead X( )

**Screenshots / GIFs / videos**
![2020-04-17_19 41 57](https://user-images.githubusercontent.com/62778379/79626253-9beaa880-80e3-11ea-807d-0c4773ade20a.png)

(If applicable, add screenshots to help explain your problem.)

**Relevant configuration files**

(The three grave accents mark the beginning and end of a code block. If there are relevant configuration files,
please paste them in the lines between the accents sothat others can see if there are any syntax errors.)

```

```

**Comment by Sataniel98** [comment] 2020-04-18 08:54
Duplicate of #759

**Closed as completed by Sataniel98** 2020-04-18 08:54 UTC
Labels: DUPLICATE
