### ISSUE TITLE
Have a bug

### ISSUE THREAD

**Issue by AaronHzy** [DRE2N/DungeonsXL#418] opened 2018-06-07 14:41 UTC
Player join the dungeons and click sign leave dungeons
Player leave the map but can not use command (/dxl leave not work)
and Console error，repeated it **↓↓↓**
`[22:33:53 WARN]: [DungeonsXL] Task #2259330 for DungeonsXL v0.16-RC-01 generated an exception
java.lang.NullPointerException: null
[22:33:53 WARN]: [DungeonsXL] Task #2265639 for DungeonsXL v0.16-RC-01 generated an exception
java.lang.NullPointerException: null
        at de.erethon.dungeonsxl.world.DGameWorld.getStartLocation(DGameWorld.java:177) ~[?:?]
        at de.erethon.dungeonsxl.player.DGamePlayer.respawn(DGamePlayer.java:739) ~[?:?]
        at de.erethon.dungeonsxl.player.DGamePlayer.ready(DGamePlayer.java:728) ~[?:?]
        at de.erethon.dungeonsxl.player.DGamePlayer.ready(DGamePlayer.java:699) ~[?:?]
        at de.erethon.dungeonsxl.player.DGamePlayer.<init>(DGamePlayer.java:100) ~[?:?]
        at de.erethon.dungeonsxl.player.CreateDInstancePlayerTask.run(CreateDInstancePlayerTask.java:64) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
[22:33:53 WARN]: [DungeonsXL] Task #2259330 for DungeonsXL v0.16-RC-01 generated an exception
java.lang.NullPointerException: null`

**Comment by Sataniel98** [comment] 2018-06-07 16:09
Duplicate of #411. This has already been fixed in the latest build. Thank you anyway for your report, please keep it up, it is helpful and appreciated.

**Closed as completed by Sataniel98** 2018-06-07 16:09 UTC
Labels: DUPLICATE
