### ISSUE TITLE
Broken Triggers

### ISSUE THREAD

**Issue by AsuDev2** [DRE2N/DungeonsXL#561] opened 2019-04-20 06:12 UTC
Killing mythicmob to trigger a sign is broken. The first time you enter a dungeon and complete it, it works fine, but once you enter the dungeon again, the sign that was triggered by the mob death in the previous instance, goes off instantly when in distance of it. 

Example:
Sign 1:
[Trigger]  
1                  
""
D4

Sign 2:
[Mob]
testmob
0,1,MM
T1

Sign 3:
[Trigger]
2
""
M testmob

Sign 4:
[Title]
&a&lComplete!
""
T2

When you complete the dungeon and leave, the next time you go into the dungeon and get in range of the sign, it will activate the title again even though you have not killed the mob yet.

**Comment by AsuDev2** [comment] 2019-04-20 06:20
I don't know if this problem stems from something else but that's what happens to me and it is very annoying.

**Comment by Sataniel98** [comment] 2019-04-20 15:25
Duplicate of #452

**Closed as completed by Sataniel98** 2019-04-20 15:25 UTC
Labels: BUG, DUPLICATE
