### ISSUE TITLE
Players frequently not be able to end a dungeon when click on the "end" sign.

### ISSUE THREAD

**Issue by k-jiang** [DRE2N/DungeonsXL#373] opened 2018-04-24 16:31 UTC
Sometimes players can not leave a finished dungeons. when clicking on the "end" sign, this is what occurs on the console:
```
[00:12:30 ERROR]: Could not pass event PlayerInteractEvent to DungeonsXL v0.16-SNAPSHOT-07
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1402]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1402]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1402]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) ~[patched_1.12.2.jar:git-Paper-1402]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) ~[patched_1.12.2.jar:git-Paper-1402]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:236) ~[patched_1.12.2.jar:git-Paper-1402]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:460) ~[patched_1.12.2.jar:git-Paper-1402]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:991) ~[patched_1.12.2.jar:git-Paper-1402]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[patched_1.12.2.jar:git-Paper-1402]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.12.2.jar:git-Paper-1402]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1402]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1402]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.2.jar:git-Paper-1402]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [patched_1.12.2.jar:git-Paper-1402]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1402]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1402]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.IllegalArgumentException: Health must be between 0 and 40.0, but was 44.0. (attribute base value: 40.0, player: VergilQ)
        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:100) ~[patched_1.12.2.jar:git-Paper-1402]
        at io.github.dre2n.dungeonsxl.player.DGlobalPlayer.reset(DGlobalPlayer.java:335) ~[DungeonsXL-0.16b7-CB1.12.2.jar:?]
        at io.github.dre2n.dungeonsxl.player.DGamePlayer.leave(DGamePlayer.java:489) ~[DungeonsXL-0.16b7-CB1.12.2.jar:?]
        at io.github.dre2n.dungeonsxl.player.DGroup.finish(DGroup.java:686) ~[DungeonsXL-0.16b7-CB1.12.2.jar:?]
        at io.github.dre2n.dungeonsxl.player.DGamePlayer.finish(DGamePlayer.java:812) ~[DungeonsXL-0.16b7-CB1.12.2.jar:?]
        at io.github.dre2n.dungeonsxl.player.DGamePlayer.finish(DGamePlayer.java:794) ~[DungeonsXL-0.16b7-CB1.12.2.jar:?]
        at io.github.dre2n.dungeonsxl.sign.EndSign.onPlayerTrigger(EndSign.java:74) ~[DungeonsXL-0.16b7-CB1.12.2.jar:?]
        at io.github.dre2n.dungeonsxl.sign.DSign.onUpdate(DSign.java:181) ~[DungeonsXL-0.16b7-CB1.12.2.jar:?]
        at io.github.dre2n.dungeonsxl.trigger.Trigger.updateDSigns(Trigger.java:113) ~[DungeonsXL-0.16b7-CB1.12.2.jar:?]
        at io.github.dre2n.dungeonsxl.trigger.InteractTrigger.onTrigger(InteractTrigger.java:50) ~[DungeonsXL-0.16b7-CB1.12.2.jar:?]
        at io.github.dre2n.dungeonsxl.sign.DSignListener.onPlayerInteract(DSignListener.java:61) ~[DungeonsXL-0.16b7-CB1.12.2.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor828.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1402]
        ... 18 more
```

I know this plugin is still in its development stage. But since it is THE only best dungeon plugin that has independent dungeon worlds feature, I'm being bombarded with players complain about they cannot earn their rewards and getting stuck inside a dungeon. What makes this odd is, in some cases, part of group members can end their dungeons successfully yet leaving some other team members left inside the dungeon world.

Tested on PaperSpigot (a fork of Spigot) 1.12.2, with DungeonsXL 0.16 build 07.
Thank you for your work on such a great project. If you need more information please let me know.

**Comment by Sataniel98** [comment] 2018-04-24 16:43
Possibly a duplicate of either #216, #239 / #271 or both. DungeonsXL currently does not support keepInventory alongside custom health scales. A fix for this is scheduled for version 0.16. Do you know if this happens without the part that says "Health must be between 0 and 40.0, but was 44.0. (attribute base value: 40.0, player: VergilQ)"?

**Comment by k-jiang** [comment] 2018-04-25 17:05
Thank you for your information! We will try to enforce maximum 20 health scale on players with BetonQuest scripts. Lets see if things are fixed.

**Comment by k-jiang** [comment] 2018-04-25 17:07
(Off topic: Your build server seems down :( The website returns 404 error when clicking on the artifacts' download links.)

**Comment by Sataniel98** [comment] 2018-04-25 18:54
I moved some projects to
```
        <dependency>
            <groupId>de.erethon</groupId>
            <artifactId>commons</artifactId>
            <version>4.1</version>
            <scope>compile</scope>
        </dependency>
...
        <repository>
            <id>dre-repo</id>
            <url>http://erethon.de/repo/</url>
        </repository>
```

Some older versions are still in the old repo though. What exactly are you looking for?

**Comment by k-jiang** [comment] 2018-04-25 23:43
This: [http://erethon.de/repo/de/erethon/dungeonsxl/](http://erethon.de/repo/de/erethon/dungeonsxl/). The download buttons are broken in this page. When clicked the website returns http-404 error code.

**Comment by Sataniel98** [comment] 2018-04-26 05:54
Thx but you can just click at the latest button at the top

**Closed as completed** 2018-04-26 23:13 UTC
Labels: DUPLICATE
