### ISSUE TITLE
4 Bugs report.

### ISSUE THREAD

**Issue by Ecilpse** [DRE2N/DungeonsXL#234] opened 2017-03-11 15:40 UTC
1. using the 'breakWhiteList' in the new Floor Configuratioin
'breakWhiteList' is not working properly. I tried to use the recently updated Floor Configuration. Whenever I tried to load the plugin it says it is not compatible with the faction plugin (which I don't use in my server). I did not see any other noticable error messages.

2. {[teleoprt] // x,y,z // <blank> // W 0.5, D 3 } sign was not working properly. I had about 60 regular mobs on the regular field and 1 boss in a boss zone(all in a same world but seperated) and I wanted to connect two seperate rooms with the teleport sign and be active only when over half of the mobs are killed. But for some reason it was not activating properly even though I killed all regular mobs on the field. please review this matter.

3. [lobby], [start] signs were not recognizing the pitch and yaw (the angle and the location of the player when he/she was placing the sign), At all cases, both signs were heading south.
same issue occured on the ./dxl portal.
I could not make these portals face East. I can manually changed it with worldedit, but it resets and faces south everytime I relaunch the server so its no use. Could you modify these signs and portals so they can respect the pitch and yaw?

4. For some reason, all players in my server could read the player death, dungeon failure messages from any dungeon. Is it possible to change this so only players within the dungeon can red these notice messages?

**Comment by Sataniel98** [comment] 2017-03-11 15:51
1. The breakWhiteList is not supposed to be working ATM and already marked as "CURRENTLY UNUSED".

2. Duplicate of #163 

3. I don't really consider this a high priority thing, but eventually yes.

4. I'll fix it

**Closed as completed** 2018-04-27 16:06 UTC
Labels: BUG, ENHANCEMENT
