### ISSUE TITLE
worldEnvironment doesn't seem to work. (1.16.3)

### ISSUE THREAD

**Issue by Cavin-V** [DRE2N/DungeonsXL#895] opened 2020-09-23 04:26 UTC
**Description**

Upon having some troubles using the [Mob] sign to spawn piglins from the 1.16 update, I opted to use command blocks.
It was at this point I discovered that piglins transform into zombified piglins if they exist in the 'overworld' for an amount of time.
For the dungeon I am creating, it is ideal that normal piglins are used, however upon adding the line: ```worldEnvironment: NETHER``` to the config for the map, nothing seems to have changed, the piglins still transform, and even the sky still looks as if its an overworld map.

**Reproduce**

1: use /dxl create to create a dungeon.
2: create a config for the map, and set worldEnvironment to NETHER.
3: spawn a piglin (either through commands or other)

**Expected behavior**

What I assume should happen, is the world itself should have nether-like qualities when the worldEnvironment is set to NETHER, however none of these can be seen in my case.

**Relevant configuration files**

In the map config (In plugins/DungeonsXL/maps/MapName)
```
keepInventoryOnEnter: true
keepInventoryOnFinish: true
keepInventoryOnEscape: true
keepInventoryOnDeath: true
foodLevel: false
timeUntilKickOfflinePlayer: 300
initialLives: 3
worldEnvironment: NETHER
messages:
  '1': Bastion
mustFinishOne:
  - Mansion
  - DwarfFortress
invitedPlayers: []
timeToNextPlayAfterFinish: 6
```

**Comment by Sataniel98** [comment] 2020-10-24 17:43
Duplicate of #805. BTW, Piglins spawned through mob signs are now automatically immune to zombification.

**Closed as completed by Sataniel98** 2020-10-24 17:43 UTC
Labels: DUPLICATE
