### ISSUE TITLE
[Feature] Compatibility with SkillAPI

### ISSUE THREAD

**Issue by Tiplish** [DRE2N/DungeonsXL#431] opened 2018-06-25 19:44 UTC
Hi,

I use a plugin named SkillAPI which have a level system. Is it possible to add a condition for entrance in dungeon, the level of the player?

**Comment by Sataniel98** [comment] 2018-06-25 22:59
Duplicate of #25. This is the second oldest unresolved issue of this project, opened in 2015 ^^"

**Closed as completed by Sataniel98** 2018-06-25 22:59 UTC
Labels: DUPLICATE

**Comment by Tiplish** [comment] 2018-06-26 07:12
Arg i've miss it :'(
