### ISSUE TITLE
2 Mobs Spawning instead of one. (The sign is correct)

### ISSUE THREAD

**Issue by gamingjuts** [DRE2N/DungeonsXL#575] opened 2019-05-19 04:20 UTC
**Description**
While playing on my server i have been using the plugin and it has done perfect, until now. For some readon it just randomly wanted to mess up and spawn 2 mobs on the sign that is set instead of spawning one. It did this once before a long time ago. So i had to shut my dungeons down. I am just not sure on how to fix it when i have it all set up correctly. BTW i do have Towny on the server, but i am just not sure on how to be able to use dungeons if towny is the main part of the server. i need suggestions. I tried perworldplugins but it just messed everything up
[//]: # (A clear and concise description of what the bug is.)

**Reproduce**

[//]: # (List steps to reproduce)

**Expected behavior**
Only spawn one mob
[//]: # (A clear and concise description of what you expected to happen.)
When i jooin the dungeon and hit the distance trigger, i expected one boss to be spawned, however a bug happened and it spawned 2
the sign is like this
[mob]
Pirate
3,1,MM
d 5
**Screenshots / GIFs / videos**

[//]: # (If applicable, add screenshots to help explain your problem.)

**Relevant configuration files**

[//]: # (Please paste the relevant configuration files in the line between the quotation marks:)

[DungeonsXL.zip](https://github.com/DRE2N/DungeonsXL/files/3194764/DungeonsXL.zip)

```

```

**Comment by gamingjuts** [comment] 2019-05-19 04:22
if you would like to join the server to see the bug for yourself (its not completely public, its in alpha) but you can do /warp dungeons and try it out, it is just weird. The first dungeon is a test. 
173.236.104.37:25590 let me know if i need to op you.

**Comment by gamingjuts** [comment] 2019-05-19 04:23
my bad the file didnt upload all the way. 
[DungeonsXL.zip](https://github.com/DRE2N/DungeonsXL/files/3194765/DungeonsXL.zip)

**Comment by gamingjuts** [comment] 2019-05-19 04:25
Here is the actual file, it didnt upload all the way, it was too big.
https://www.dropbox.com/s/5ssjw8pyqtb3naw/DungeonsXL.zip?dl=0

**Comment by Sataniel98** [comment] 2019-05-19 08:41
Most likely a duplicate of #475. Signs must be broken, editing through a plugin that modifies signs e.g. on right click does not remove the underlying action point and you end up with two dungeon signs at the same location.

**Closed as completed** 2020-03-21 18:34 UTC
