### ISSUE TITLE
DungeonsXL not starting/working?

### ISSUE THREAD

**Issue by SimianMussel92** [DRE2N/DungeonsXL#786] opened 2020-05-03 18:53 UTC
**Description**
On start of the server, it doesnt start up properly, as it gives me errors, and some plugins that have compatibility with DungeonsXL also throw errors on trying to compat with them. As soon as I try to create a dungeon, it generates an internal error and every time any player moves/look, it throws errors to the console.

**Reproduce**
Truth be told, its a 1.15.2 server, and just by starting it starts the problems. It makes more errors as soon as I try to make a new dungeon (ex. /dxl create Goblin).

**Expected behavior**
A new map for a dungeon.

**Screenshots / GIFs / videos**
None. But I can give a pastebin of the startup log.
https://pastebin.com/T3Ae5NJ0

**Comment by Sataniel98** [comment] 2020-05-03 19:52
Duplicate of #784.

**Closed as completed by Sataniel98** 2020-05-03 19:52 UTC
Labels: DUPLICATE
