### ISSUE TITLE
Unlimited lives

### ISSUE THREAD

**Issue by Schwanzz** [DRE2N/DungeonsXL#440] opened 2018-07-07 14:44 UTC
### Expected behavior
When there are no lives remaining, the player should get kicked from the instance but not the whole group.

### Actual behavior
When the lives are at 0, the player who dies at 1 life remaining gets kicked. After that, the other players can die unlimited times and won't get kicked.

### Steps to reproduce
Make a group with 5 lives, use 2 players, the first one who dies when out of lives gets kicked, the other one gets unlimited lives.

**Comment by Sataniel98** [comment] 2018-07-07 16:12
Is it possible that this is a duplicate of #384?

**Comment by Schwanzz** [comment] 2018-07-09 12:32
It is not a duplicate of #384.

I have not combined any player lifes with group lifes.

The only thing I have setup is initial group lifes: 5

**Comment by Sataniel98** [comment] 2018-07-13 20:39
Thanks, fixed!

**Closed as completed** 2018-07-13 20:38 UTC
Labels: BUG, CONFIRMED
