### ISSUE TITLE
Dungeon runs as if it was in edit mode. (Also KeepInventory not working?)

### ISSUE THREAD

**Issue by UnendingNight** [DRE2N/DungeonsXL#648] opened 2019-08-14 05:37 UTC
**Description**

I created my single floor dungeon normally in /dxl edit mode, I made the signs with proper syntax and when ran in /dxl test it the dungeon ran normally. (Mobs spawned, Rewardchests worked, etc.) After I save the world and create a portal/group for it, upon entering the signs are all visible and they do not function as they should. Mobs do not spawn, etc. Only in test mode does the dungeon work properly. 

Also on a lesser note KeepInventory is not working. I made at config.yml and put it into my plugins/DungeonsXL/maps/{your map} folder but to no avail. You can see the contents of that config below.

**Relevant configuration files**

I haven't changed anything else concerning config files besides adding this config.yml to my map's name folder.

```
# Shall players play the dungeon with their own items or do you want to use classes?
keepInventoryOnEnter: true
# Shall players lose their items when they die (do not mix up this with "onEscape"!)?
keepInventoryOnDeath: true
# Shall players keep their inventory when they finish the dungeon?
keepInventoryOnFinish: true
# Shall players keep their inventory when they leave the dungeon without succeeding?
keepInventoryOnEscape: true
```

**Comment by Sataniel98** [comment] 2019-08-14 10:13
Sounds like the game isn't started. Did you add and trigger a ready sign?

**Comment by UnendingNight** [comment] 2019-08-14 14:38
> Sounds like the game isn't started. Did you add and trigger a ready sign?

Oh. well I feel stupid now, that fixed that issue. Still cant seem to get it to run with keep inventory however. Thanks for the help

**Comment by Sataniel98** [comment] 2019-08-19 22:45
keepInventory not working is a duplicate of #647. As far as I know, it doesn't happen in the stable releases but only in the development builds.

**Closed as completed by Sataniel98** 2019-08-19 22:45 UTC
Labels: QUESTION
