### ISSUE TITLE
Unable to leave, once able to corrupts map.

### ISSUE THREAD

**Issue by Phoenixmrn** [DRE2N/DungeonsXL#344] opened 2017-12-20 17:44 UTC
We have noticed this issue a few times when players become stuck, in our case the primary issue is the mob trigger.
When a player is stuck and they do /DXL leave it will kick them from their group but not the dungeon. They then become stuck even worse. Sometimes doing /dxl leave a second time works but not always. We cannot force TP them out they cannot use any tp or home commands. We cannot kick them from the dungeon.
The only way we have found to get them out of if the dungeon is to do a /dxl reload, while they are in there. Then kick them from the dungeon.

Unfortunately when this happens it kills the dungeon map. Anyone trying to run the dungeon is teleported to a random spot in a copy of one of our other worlds in a dungeon "state".
They are not in that actual world, their items are removed as if the dungeon started, and they cannot use normal world commands.

In some cases deleting this new world in the dxl folder works, however this instance it has not. Previously when deleting this new created world didnt work we had to recreate each broken map. However we are hoping tonight we can fix it with a backup we saved a week ago.

**Comment by Sataniel98** [comment] 2018-05-12 22:03
Duplicate of #396

**Closed as completed by Sataniel98** 2018-05-12 22:03 UTC
Labels: BUG, DUPLICATE
