### ISSUE TITLE
[M]ob death Triggers no invalid

### ISSUE THREAD

**Issue by Niinnee** [DRE2N/DungeonsXL#461] opened 2018-08-18 06:41 UTC
[//]: # (Welcome to the DungeonsXL issue tracker.)
[//]: # (Please use the following template for bug reports:)

### Steps to reproduce

[//]: # (Please use the following template for feature requests:)

### Possible use cases

[//]: # (Feel free to ask comprehension questions without using one of the templates above.)
[//]: # (Please don't hesitate to open one issue per issue instead of putting thematically unrelated problems together in one.)
Trigger use [M (MythicMobs mob) ] Some things will be invalid
For example: [Title], [CMD]

[Title]
&c&lXXXXXX
&6&lXXXXXX
M kongjuzhilang
[CMD]
lk
1,OP
M kongjuzhilang
These are not working properly

[Teleport] Can be executed normally

**Comment by Sataniel98** [comment] 2018-08-23 07:44
Duplicate of #452

**Closed as completed by Sataniel98** 2018-08-23 07:44 UTC
Labels: DUPLICATE
