### ISSUE TITLE
WhitelistedCommands & Reload internal error

### ISSUE THREAD

**Issue by Poweringg** [DRE2N/DungeonsXL#136] opened 2016-08-17 00:01 UTC
Hi, 

**1.) How can i set whitelisted commands for players in dungeon?**
I'm trying this (help, msg):

```
configVersion: 11
language: czech
enableEconomy: false
tutorial:
  activated: false
  dungeon: tutorial
  startGroup: default
  endgroup: player
groupColorPriority:
- 11
- 14
- 4
- 5
- 10
- 1
- 0
- 15
announcementInterval: 30.0
sendFloorTitle: true
externalMobProviders: {}
maxInstances: 10
tweaksEnabled: false
secureMode:
  enabled: true
  openInventories: false
  dropItems: false
  checkInterval: 5.0
  editCommandWhiteList:
    - help
    - msg
backupMode: ON_DISABLE_AND_SAVE
editPermissions: []
default: {}
```

**2.) When i typed /DXL RELOAD in chat, i got this:**
![bez nazvu](https://cloud.githubusercontent.com/assets/15527318/17719931/5998f170-641e-11e6-979c-2cb19075bd46.png)
Sometimes i got this in other dxl commands, sometimes it reloads propertly

**Comment by Sataniel98** [comment] 2016-08-17 10:20
Duplicate of #121 
The global config is for edit worlds, for game worlds, use the default section or the floor configuration itself:

```
default:
  gameCommandWhitelist:
    - help
    - msg
```

**Closed as completed by Sataniel98** 2016-08-17 10:20 UTC
Labels: DUPLICATE, QUESTION
