### ISSUE TITLE
End sign bugs.

### ISSUE THREAD

**Issue by WillPowerCraft** [DRE2N/DungeonsXL#242] opened 2017-03-14 20:13 UTC
End sign not work.

> [End]
>
>
>

case:
with hand with out any item end sign not work

case:
with out OP perms sign work in 1%. and never work if in floor playing few players in group.
with OP sign work - chat ure end waiting mates - mates wtih out OP click on sign and that do nothing.
we can only /dxl leave to exit floor (((

ure should test work all mechanics with out OP and with player permissions...

and if i have some worng with perms - pls answer what perms need to players to End sign work true?

i hope new build near with some hotfixes cuz i wanna continue use that plugin on live server...

**Comment by Sataniel98** [comment] 2017-09-22 01:51
Duplicate of #216

**Closed as completed** 2017-09-22 01:51 UTC
Labels: DUPLICATE
