### ISSUE TITLE
One player able to join the same group twice / Join multiple groups

### ISSUE THREAD

**Issue by Wihunda** [DRE2N/DungeonsXL#118] opened 2016-07-26 23:09 UTC
If a player activates a sign twice, it lists their name twice in the group;

Also, if a player clicks one sign, then clicks another group sign, they can be in both groups.

**Comment by Sataniel98** [comment] 2016-07-26 23:27
Duplicate of #77 - thank you, though :)

**Closed as completed by Sataniel98** 2016-07-26 23:27 UTC
Labels: DUPLICATE
