### ISSUE TITLE
Phatloot RewardChest support.

### ISSUE THREAD

**Issue by Maitlans** [DRE2N/DungeonsXL#914] opened 2020-10-30 09:04 UTC
**Please describe the use case or the problem your request is related to.**

Phatloot is an extremely useful rewards plugin with many features & customization used by a lot of popular plugins such as Mythicmobs & Quests. It can create very specific and special unique ways to distribute rewards. Phatloot is like the Mythicmobs of chest items.

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/51733032/97680203-b4615580-1a6c-11eb-8165-e8632798b7ba.png)
For Phatloots to be supported with DungeonsXL, I think it'll do a lot of good such as the customization, possibilities and increase the creativity.

Thank you, hope it can be considered.

**Comment by Sataniel98** [comment] 2020-10-30 12:39
Duplicate of #690.

Yes, I understand people like PhatLoots and are used to it. But an integration would have to delay actually giving the loot until the dungeon ends. Not only for keepInventory=false dungeons, but also for keepInventory=true, since we need to prevent people going into the dungeon for the first few easy loot chests and then leaving in order to avoid the typically longer timeToNextPlayAfterFinish delay.

So we could either use the command to give loot to players who finish in the end, which isn't that hard to realize, but probably not what you're hoping for. Or we could use chests and actually catch the loot when it's given to the player and withhold it until the dungeon finishs. If that's possible depends on PhatLoots' API.

I'm open for a solution that does the latter, but I won't work on it myself since it's a lot of work for a feature that mostly already exists built-in.

**Comment by Maitlans** [comment] 2020-11-01 03:07
I see what you mean, I appreciate the response.

**Closed as completed** 2020-11-01 12:28 UTC
Labels: DUPLICATE
