### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by AaronHzy** [DRE2N/DungeonsXL#415] opened 2018-06-05 12:39 UTC
Players join the Dungeons
Console printing error

`[20:36:19 ERROR]: Could not pass event EntityDamageByEntityEvent to DungeonsXL v0.16-RC-01
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:94) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:581) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:484) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:613) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity0(EntityLiving.java:1369) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:887) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.EntityMonster.damageEntity(EntityMonster.java:44) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.EntityZombie.damageEntity(EntityZombie.java:163) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.EntityArrow.a(EntityArrow.java:295) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.EntityArrow.B_(EntityArrow.java:203) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.EntityTippedArrow.B_(EntityTippedArrow.java:86) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1771) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.World.h(World.java:1741) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1562) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:678) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:914) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
Caused by: java.lang.NullPointerException
        at de.erethon.dungeonsxl.world.DWorldListener.onEntityDamage(DWorldListener.java:134) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1057.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        ... 24 more
`

**Comment by Sataniel98** [comment] 2018-06-05 21:30
Duplicate of #414. Could you, however, please provide some more information about how exactly that happens? Ideally, a copy of your whole DungeonsXL folder or at least the respective configs?

**Comment by AaronHzy** [comment] 2018-06-06 10:02
I have only one map
The player join the wrong map
like this -> [https://imgchr.com/i/CHPDII](https://imgchr.com/i/CHPDII)

player exits and join again
Join the proper map
like this -> [https://imgchr.com/i/CHPWLQ](https://imgchr.com/i/CHPWLQ)

**Comment by Sataniel98** [comment] 2018-06-07 09:33
I don't see the problem there? Could you provide more information about your setup please, like your configs and, if possible, the map?

**Comment by DrOreo002** [comment] 2018-06-08 03:54
I also got this error log. And I don't know why..

**Comment by Sataniel98** [comment] 2018-06-08 13:17
@DrOreo002 I am sorry to hear that, but I can't reproduce it. Please help me out with some more information, especially your configs.

**Comment by DrOreo002** [comment] 2018-06-09 03:11
My config?. Okay
`configVersion: 15
language: english
enableEconomy: false
tutorial:
  activated: false
  dungeon: tutorial
  startGroup: default
  endgroup: player
groupColorPriority:
- DARK_BLUE
- LIGHT_RED
- YELLOW
- LIGHT_GREEN
- PURPLE
- ORANGE
- WHITE
- BLACK
- LIGHT_BLUE
- DARK_GREEN
- DARK_RED
- LIGHT_GRAY
- CYAN
- MAGENTA
- DARK_GRAY
announcementInterval: 30.0
sendFloorTitle: true
externalMobProviders: {}
resourcePacks: {}
maxInstances: 5
tweaksEnabled: false
secureMode:
  enabled: trye
  openInventories: false
  dropItems: true
  checkInterval: 5.0
  editCommandWhitelist: []
backupMode: ON_DISABLE_AND_SAVE
editPermissions: []
default: {}
chatEnabled: true
chatFormatGame: '&7[&cDungeon &7] %group_color%%player_name%: &r'
chatFormatGroup: '&2%group_color%[%group_name%] %player_name%: &r'
chatFormatSpy: '&2[Chat Spy] %player_name%: &r'
globalDeathMessagesDisabled: true
`

**Comment by Sataniel98** [comment] 2018-06-09 10:16
Do you use a dungeon / floor configuration?

**Comment by Sataniel98** [comment] 2018-06-10 21:10
Did you teleport players from the main worlds into an instance?

**Comment by DrOreo002** [comment] 2018-06-11 12:56
1. No
2. Prob, player on my server has permission to /tphere. This should be fixed for me, because I have a custom plugin to disable any command when the player is on a dungeon

**Comment by Sataniel98** [comment] 2018-06-11 22:16
Thank you, that was very helpful. I am positive this is fixed as of build 638.

**Closed as completed by Sataniel98** 2018-06-11 22:16 UTC
Labels: DUPLICATE
