### ISSUE TITLE
Junk Instance

### ISSUE THREAD

**Issue by skyfyx** [DRE2N/DungeonsXL#550] opened 2019-03-13 11:54 UTC
Hello , 

when my server restarted this morning. There was that written in the console and a whole bunch of dungeon files.

`[08:04:46] [Server thread/INFO]: [DungeonsXL] [0;33;22mWarning: An unrecognized junk instance ([0;31;22mDXL_Game_0[0;33;22m) has been found, but could not be deleted.[m

[08:04:46] [Server thread/INFO]: [DungeonsXL] [0;33;22mWarning: An unrecognized junk instance ([0;31;22mDXL_Game_1[0;33;22m) has been found, but could not be deleted.[m

[08:04:46] [Server thread/INFO]: [DungeonsXL] [0;33;22mWarning: An unrecognized junk instance ([0;31;22mDXL_Game_2[0;33;22m) has been found, but could not be deleted.[m`

26 other 

Thanks for your help , it's the latest version 0.17.5

**Comment by Sataniel98** [comment] 2019-03-13 18:55
Hi, thank you for the report but this is a duplicate of #506.

**Closed as completed by Sataniel98** 2019-03-13 18:55 UTC
Labels: DUPLICATE
