### ISSUE TITLE
How do you control which direction the nether portal blocks faces?

### ISSUE THREAD

**Issue by ValleVonMemester** [DRE2N/DungeonsXL#710] opened 2020-02-22 10:14 UTC
You wrote somewhere that it depends on what direction the player is facing. If I want them to go from east to west, what direction should I face and when does the direction I face matter (is it when you execute the command or when you mark the corners of the portal with the wooden sword?)

**Comment by ValleVonMemester** [comment] 2020-02-22 10:48
edit: fixed with worldedit

//replace minecraft:nether_portal minecraft:nether_portal[axis=z]

**Comment by Sataniel98** [comment] 2020-02-22 12:55
Duplicate of #668

**Closed as completed by Sataniel98** 2020-02-22 12:55 UTC
Labels: DUPLICATE
