### ISSUE TITLE
Problem trying dungeon 

### ISSUE THREAD

**Issue by nicolasecm** [DRE2N/DungeonsXL#777] opened 2020-04-27 20:16 UTC
**Description**

When completing the dungeon it can not be done again, when it tries again it appears at the point 0,0,0 of the seed in which the dungeon is located, I do not know if it is because I have the worldGuard plugin and it can generate a mistake making it a new seed, I am using version for 1.13.2

**Reproduce**

(List steps to reproduce, e.g.:
1. Enter the dungeon
2. Finish the dungeon
3. Entering the dungeon again
4. Spawnpoint in 0,0,0 and if I get to the lobby it won't start

**Expected behavior**

I want that at the end of the dungeon you can go back in as many times as you want

**Screenshots / GIFs / videos**

https://user-images.githubusercontent.com/4656406/80416426-b702a880-8899-11ea-835b-6ba67400d483.png
```

```

**Comment by Sataniel98** [comment] 2020-05-01 12:31
I can't reproduce this :/ Anyway, some changes have been made to the instantiation system recently that might make this obsolete, so I'll close this for now. If it still happens, please let me know.

**Closed as completed by Sataniel98** 2020-05-01 12:31 UTC
Labels: BUG, CAN'T REPRODUCE
