### ISSUE TITLE
Problem with MySQLPlayerDataBridge + Heroes Legacy + DungeonsXL

### ISSUE THREAD

**Issue by GerwinVerkerk** [DRE2N/DungeonsXL#727] opened 2020-03-21 12:43 UTC
Hi,

I am running a 1.12.2 spigot minecraft server on a Bungeecord network. I am using MySQLPlayerDataBridge in order to sync inventories accross the different servers in the network. Everything works fine when I add DungeonsXL since MySQLPlayerDataBridge knows how to handle this plugin in the DB. However, when I add Heroes Legacy, an error occurs that is caused by the DungeonsXL plugin. When I remove DungeonsXL, the error is gone. Also when I remove Heroes Legacy and keep DungeonsXL, the error is gone.

It seems that DungeonsXL and Heroes are in conflict with eachother with the MySQLPlayerDataBridge running. This is the error message I get, I hope you can help me figure it out:

The error is generated when I try to /stop the server.
However, when the DB is created and no players have joined, /stop works.
Once a player is in the DB, the error will be given.

https://imgur.com/a/g9FMs07

**Comment by Sataniel98** [comment] 2020-03-21 13:35
As we discussed on the Discord server, the problem is caused by an error in the integration of MySQLPlayerDataBridge so I'll close this for now. If it turns out there is something wrong with my API or if the devs need help with it, free feel to get back to me.

**Closed as completed by Sataniel98** 2020-03-21 13:35 UTC
Labels: INVALID, INCOMPATIBILITY
