### ISSUE TITLE
Requirements charge you for every floor.

### ISSUE THREAD

**Issue by Davedave000** [DRE2N/DungeonsXL#913] opened 2020-10-29 07:47 UTC
(Please follow this template, as doing so saves both you and me a lot of time.
Issues that don't follow the template may be closed.)

**Description**

Even if you put the fee requirements in the first floor, DXL will still take money from your balance for every floor you visit.

**Reproduce**

1. Create a multifloor dungeon.
2. Add a config.yml file to the first map.
3. Add a 'feeMoney' requirement.
4. Playtest the dungeon without OP. It should charge you for each floor.

**Expected behavior**

It should only charge me for the first floor.

**Screenshots / GIFs / videos**

![image](https://user-images.githubusercontent.com/56517317/97539851-ec3e9f00-197f-11eb-8b83-7ef2324fb2dc.png)

**Relevant configuration files**

config.yml for the first floor:
```
requirements:
  forbiddenItems:
  - ENDER_PEARL
  - ELYTRA
  feeMoney: 9
```
yml file for the entire dungeon:
```
# The first floor the players enter.
# Needs at least lobby, ready, start and end signs.
startFloor: Craggy_Coast_1
endFloor: Craggy_Coast_6
floors:
- Craggy_Coast_2
- Craggy_Coast_3
- Craggy_Coast_4
- Craggy_Coast_5
floorCount: 2
removeWhenPlayed: true
overrideValues:
  timeToNextLoot: 2
  time: 6000
configVersion: 1

```

**Comment by Sataniel98** [comment] 2020-10-29 13:45
Cannot reproduce this. The requirements were checked in the first floor and that was it.
![2020-10-29_14 42 46](https://user-images.githubusercontent.com/8921300/97581676-20a07280-19f5-11eb-935c-f388f62f817c.png)
First two checks were in the first floor (once on join & start), no checks were made in the other floors. I _could_ reproduce that removeWhenPlayed and floorCount were ignored though.

**Comment by Davedave000** [comment] 2020-10-29 17:28
I tried looking into it more and I didn't see any errors in console. Maybe the fee being charged on every floor is some kind of incompatibility with another plugin?

**Comment by Sataniel98** [comment] 2020-10-29 17:43
I can't imagine it is.

**Comment by Davedave000** [comment] 2020-10-29 22:22
Now that I look at your screenshot, it doesn't look like the plugin charged you at all.

**Comment by Sataniel98** [comment] 2020-10-30 00:00
Yes, because I'm OP. But it printed the check messages and that's what matters.

**Comment by Davedave000** [comment] 2020-10-30 11:23
I decided to check and the price requirements don't print at all if you're OP.
![image](https://user-images.githubusercontent.com/56517317/97699239-0901d200-1a67-11eb-976a-d8ee8ea5f738.png)
Maybe the forbiddenItems check is fine, but it's feeMoney specifically that's the problem? Try testing it again without op, and with an economy plugin + vault.

**Closed as completed** 2021-08-21 21:47 UTC
Labels: BUG, CAN'T REPRODUCE
