### ISSUE TITLE
Ready Sign error in 1.14.4

### ISSUE THREAD

**Issue by fatmanjumprope** [DRE2N/DungeonsXL#633] opened 2019-08-01 09:28 UTC
In two of my dungeons when a player clicks a ready sign the console gives an error and the player won't be able to start the dungeon. All other dungeon ready signs seem to be working except in 2 of the dungeons. I've tried moving the signs around but it didn't change anything.

I was expecting the dungeon to start but unfortunately it did not.

Below is the given error when one of the two Ready signs are clicked.

```
>.... [09:34:13 ERROR]: Could not pass event PlayerInteractEvent to DungeonsXL v0.18-SNAPSHOT-771
java.lang.IllegalArgumentException: Block is not Directional or Rotatable
at de.erethon.dungeonsxl.adapter.block.BlockAdapterBlockData.getFacing(BlockAdapterBlockData.java:65) ~[?:?]
at de.erethon.dungeonsxl.sign.LocationSign.onInit(LocationSign.java:41) ~[?:?]
at de.erethon.dungeonsxl.sign.TeleportSign.onInit(TeleportSign.java:53) ~[?:?]
at de.erethon.dungeonsxl.world.DGameWorld.startGame(DGameWorld.java:439) ~[?:?]
at de.erethon.dungeonsxl.player.DGroup.startGame(DGroup.java:822) ~[?:?]
at de.erethon.dungeonsxl.player.DGamePlayer.ready(DGamePlayer.java:714) ~[?:?]
at de.erethon.dungeonsxl.sign.lobby.ReadySign.ready(ReadySign.java:161) ~[?:?]
at de.erethon.dungeonsxl.sign.lobby.ReadySign.onPlayerTrigger(ReadySign.java:117) ~[?:?]
at de.erethon.dungeonsxl.sign.DSign.onUpdate(DSign.java:185) ~[?:?]
at de.erethon.dungeonsxl.trigger.Trigger.updateDSigns(Trigger.java:109) ~[?:?]
at de.erethon.dungeonsxl.trigger.InteractTrigger.onTrigger(InteractTrigger.java:50) ~[?:?]
at de.erethon.dungeonsxl.sign.DSignListener.onPlayerInteract(DSignListener.java:69) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor315.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[server.jar:git-Paper-149]
at org.bukkit.plugin.EventExecutor$$Lambda$2660.0000000054B06DF0.execute(Unknown Source) ~[?:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[server.jar:git-Paper-149]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[server.jar:git-Paper-149]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[server.jar:git-Paper-149]
at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:445) ~[server.jar:git-Paper-149]
at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:440) ~[server.jar:git-Paper-149]
at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1361) ~[server.jar:git-Paper-149]
at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[server.jar:git-Paper-149]
at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[server.jar:git-Paper-149]
at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[server.jar:git-Paper-149]
at net.minecraft.server.v1_14_R1.PlayerConnectionUtils$$Lambda$3769.000000003805D440.run(Unknown Source) ~[?:?]
at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[server.jar:git-Paper-149]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[server.jar:git-Paper-149]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[server.jar:git-Paper-149]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[server.jar:git-Paper-149]
at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1012) ~[server.jar:git-Paper-149]
at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1005) ~[server.jar:git-Paper-149]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[server.jar:git-Paper-149]
at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:989) ~[server.jar:git-Paper-149]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:922) ~[server.jar:git-Paper-149]
at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]
```

**Comment by Sataniel98** [comment] 2019-08-01 13:54
The bug is known. To my knowledge, it is only caused by script signs that include location signs (teleport, lobby, start) at priorities other than the first. It will be resolved in combination with the sign and trigger system rewrite (#452), but this might take a while to be merged into the master.

**Comment by fatmanjumprope** [comment] 2019-08-01 20:15
Good to know it's in the to do list :) Thanks as always for taking the time to help me out.

**Comment by Sataniel98** [comment] 2019-08-01 21:23
I'll keep it open as long as it's not resolved.

**Comment by Aeyori** [comment] 2019-08-21 03:47
I believe I'm also experiencing the same error

**Comment by TheRealTamama** [comment] 2020-03-30 15:54
[Dont Reply] Just an Update of the current issues, not complaining just giving you more data just in case.

```
30.03 23:49:47 [Server] ERROR Could not pass event PlayerInteractEvent to DungeonsXL v0.18-SNAPSHOT-819
30.03 23:49:47 [Server] INFO java.lang.IllegalArgumentException: Block is not Directional or Rotatable
30.03 23:49:47 [Server] INFO at de.erethon.dungeonsxl.adapter.block.BlockAdapterBlockData.getFacing(BlockAdapterBlockData.java:65) ~[?:?]
30.03 23:49:47 [Server] INFO at de.erethon.dungeonsxl.sign.LocationSign.onInit(LocationSign.java:41) ~[?:?]
30.03 23:49:47 [Server] INFO at de.erethon.dungeonsxl.sign.TeleportSign.onInit(TeleportSign.java:53) ~[?:?]
30.03 23:49:47 [Server] INFO at de.erethon.dungeonsxl.world.DGameWorld.startGame(DGameWorld.java:439) ~[?:?]
30.03 23:49:47 [Server] INFO at de.erethon.dungeonsxl.player.DGroup.startGame(DGroup.java:822) ~[?:?]
30.03 23:49:47 [Server] INFO at de.erethon.dungeonsxl.player.DGamePlayer.ready(DGamePlayer.java:714) ~[?:?]
30.03 23:49:47 [Server] INFO at de.erethon.dungeonsxl.sign.lobby.ReadySign.ready(ReadySign.java:161) ~[?:?]
30.03 23:49:47 [Server] INFO at de.erethon.dungeonsxl.sign.lobby.ReadySign.onPlayerTrigger(ReadySign.java:117) ~[?:?]
30.03 23:49:47 [Server] INFO at de.erethon.dungeonsxl.sign.DSign.onUpdate(DSign.java:184) ~[?:?]
30.03 23:49:47 [Server] INFO at de.erethon.dungeonsxl.trigger.Trigger.updateDSigns(Trigger.java:109) ~[?:?]
30.03 23:49:47 [Server] INFO at de.erethon.dungeonsxl.trigger.InteractTrigger.onTrigger(InteractTrigger.java:50) ~[?:?]
30.03 23:49:47 [Server] INFO at de.erethon.dungeonsxl.sign.DSignListener.onPlayerInteract(DSignListener.java:69) ~[?:?]
30.03 23:49:47 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor715.execute(Unknown Source) ~[?:?]
30.03 23:49:47 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-243]
30.03 23:49:47 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-243]
30.03 23:49:47 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-243]
30.03 23:49:47 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-243]
30.03 23:49:47 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:454) ~[patched_1.14.4.jar:git-Paper-243]
30.03 23:49:47 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:443) ~[patched_1.14.4.jar:git-Paper-243]
30.03 23:49:47 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1361) ~[?:git-Paper-243]
30.03 23:49:47 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.14.4.jar:git-Paper-243]
30.03 23:49:47 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.14.4.jar:git-Paper-243]
30.03 23:49:47 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-243]
30.03 23:49:47 [Server] INFO at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-243]
30.03 23:49:47 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-243]
30.03 23:49:47 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-243]
30.03 23:49:47 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-243]
```

**Comment by Sataniel98** [comment] 2020-05-01 21:00
Fixed.

**Closed as completed by Sataniel98** 2020-05-01 21:00 UTC
Labels: BUG, CONFIRMED
