### ISSUE TITLE
Running or editing Nether map after server restart makes it a flat normal world

### ISSUE THREAD

**Issue by Esronn** [DRE2N/DungeonsXL#888] opened 2020-09-08 06:54 UTC
(Please follow this template, as doing so saves both you and me a lot of time.
Issues that don't follow the template may be closed.)

**Description**

I imported a nether map into dxl. Works fine to play and edit after that, but after a server restart or DXL reload it makes the world an empty flat normal world.

Even tho the map config in DXL states Nether as environment.

I am not using any Nether blocks in the world, only the map type and biomes.

**Reproduce**

(List steps to reproduce, e.g.:
1. import a nether map with /dxl import
2. reload plugin or restart server
3. Edit or play the map.

**Expected behavior**

I expected the map to still be a nether world with the build.

**Relevant configuration files**

Map config
```
invitedPlayers: []
worldEnvironment: NETHER

```
DXL console log on startup
```
[05:03:10] [Server thread/INFO]: [DungeonsXL] Enabling DungeonsXL v0.18-SNAPSHOT-1003
[05:03:10] [Server thread/INFO]: [DungeonsXL] [##########[DungeonsXL]##########]
[05:03:10] [Server thread/INFO]: [DungeonsXL] Internals: [v1_16_R2]
[05:03:10] [Server thread/INFO]: [DungeonsXL] Paper API: [true]
[05:03:10] [Server thread/INFO]: [DungeonsXL] Economy: [true]
[05:03:10] [Server thread/INFO]: [DungeonsXL] Permissions: [true]
[05:03:10] [Server thread/INFO]: [DungeonsXL] Metrics: [https://bstats.org/plugin/bukkit/DungeonsXL]
[05:03:10] [Server thread/INFO]: [DungeonsXL] SpigotMC ID: [9488]
[05:03:10] [Server thread/INFO]: [DungeonsXL] [###############################]
[05:03:10] [Server thread/WARN]: [DungeonsXL] Support for Minecraft 1.14 and higher is experimental. Do not use this in a production environment.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material CRIMSON_NYLIUM. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material WARPED_NYLIUM. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material CRIMSON_PLANKS. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material WARPED_PLANKS. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material NETHER_GOLD_ORE. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material CRIMSON_STEM. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material WARPED_STEM. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material STRIPPED_CRIMSON_STEM. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material STRIPPED_WARPED_STEM. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material STRIPPED_CRIMSON_HYPHAE. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material STRIPPED_WARPED_HYPHAE. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material CRIMSON_HYPHAE. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material WARPED_HYPHAE. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material CRIMSON_FUNGUS. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material WARPED_FUNGUS. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material CRIMSON_ROOTS. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material WARPED_ROOTS. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material NETHER_SPROUTS. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material WEEPING_VINES. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material TWISTING_VINES. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material CRIMSON_SLAB. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material WARPED_SLAB. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material CRIMSON_PRESSURE_PLATE. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material WARPED_PRESSURE_PLATE. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material POLISHED_BLACKSTONE_PRESSURE_PLATE. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material CRIMSON_FENCE. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material WARPED_FENCE. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material SOUL_SOIL. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material BASALT. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material POLISHED_BASALT. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material SOUL_TORCH. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material CRIMSON_TRAPDOOR. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material WARPED_TRAPDOOR. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material CHAIN. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material CRIMSON_FENCE_GATE. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material WARPED_FENCE_GATE. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material CRACKED_NETHER_BRICKS. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material CHISELED_NETHER_BRICKS. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material CRIMSON_STAIRS. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material WARPED_STAIRS. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material BLACKSTONE_WALL. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material POLISHED_BLACKSTONE_WALL. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material POLISHED_BLACKSTONE_BRICK_WALL. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material CRIMSON_BUTTON. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material WARPED_BUTTON. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material POLISHED_BLACKSTONE_BUTTON. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material QUARTZ_BRICKS. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material WARPED_WART_BLOCK. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material CRIMSON_DOOR. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material WARPED_DOOR. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material NETHERITE_INGOT. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material NETHERITE_SCRAP. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material NETHERITE_SWORD. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material NETHERITE_SHOVEL. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material NETHERITE_PICKAXE. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material NETHERITE_AXE. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material NETHERITE_HOE. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material NETHERITE_HELMET. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material NETHERITE_CHESTPLATE. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material NETHERITE_LEGGINGS. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material NETHERITE_BOOTS. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material CRIMSON_SIGN. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material WARPED_SIGN. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material BEE_SPAWN_EGG. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material HOGLIN_SPAWN_EGG. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material PIGLIN_SPAWN_EGG. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material PIGLIN_BRUTE_SPAWN_EGG. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material STRIDER_SPAWN_EGG. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material ZOGLIN_SPAWN_EGG. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material ZOMBIFIED_PIGLIN_SPAWN_EGG. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material WARPED_FUNGUS_ON_A_STICK. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material MUSIC_DISC_PIGSTEP. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material PIGLIN_BANNER_PATTERN. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material SOUL_LANTERN. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material SOUL_CAMPFIRE. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material SHROOMLIGHT. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material HONEYCOMB. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material BEE_NEST. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material BEEHIVE. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material HONEY_BOTTLE. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material HONEY_BLOCK. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material HONEYCOMB_BLOCK. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material LODESTONE. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material NETHERITE_BLOCK. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material ANCIENT_DEBRIS. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material TARGET. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material CRYING_OBSIDIAN. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material BLACKSTONE. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material BLACKSTONE_SLAB. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material BLACKSTONE_STAIRS. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material GILDED_BLACKSTONE. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material POLISHED_BLACKSTONE. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material POLISHED_BLACKSTONE_SLAB. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material POLISHED_BLACKSTONE_STAIRS. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material CHISELED_POLISHED_BLACKSTONE. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material POLISHED_BLACKSTONE_BRICKS. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material POLISHED_BLACKSTONE_BRICK_SLAB. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material POLISHED_BLACKSTONE_BRICK_STAIRS. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material CRACKED_POLISHED_BLACKSTONE_BRICKS. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material RESPAWN_ANCHOR. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material SOUL_FIRE. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material SOUL_WALL_TORCH. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material WEEPING_VINES_PLANT. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material TWISTING_VINES_PLANT. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material CRIMSON_WALL_SIGN. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material WARPED_WALL_SIGN. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material POTTED_CRIMSON_FUNGUS. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material POTTED_WARPED_FUNGUS. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material POTTED_CRIMSON_ROOTS. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the material POTTED_WARPED_ROOTS. Please update your implementation if possible.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn has a representation of the material ZOMBIE_PIGMAN_SPAWN_EGG that does not exist in Bukkit.
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the entity ZOMBIFIED_PIGLIN. Please update your implementation if possible!
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the entity BEE. Please update your implementation if possible!
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the entity HOGLIN. Please update your implementation if possible!
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the entity PIGLIN. Please update your implementation if possible!
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the entity STRIDER. Please update your implementation if possible!
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the entity ZOGLIN. Please update your implementation if possible!
[05:03:10] [Server thread/INFO]: [DungeonsXL] [WARNING] Caliburn lacks a built-in representation of the entity PIGLIN_BRUTE. Please update your implementation if possible!

```

The console log when you do step 3 in the reproduce list.
```
[08:36:05] [Server thread/INFO]: Znitsarn issued server command: /dxl play Moria
[08:36:09] [Server thread/INFO]: -------- World Settings For [DXL_Game_6] --------
[08:36:09] [Server thread/INFO]: Experience Merge Radius: 3.0
[08:36:09] [Server thread/INFO]: Cactus Growth Modifier: 100%
[08:36:09] [Server thread/INFO]: Cane Growth Modifier: 100%
[08:36:09] [Server thread/INFO]: Melon Growth Modifier: 100%
[08:36:09] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[08:36:09] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[08:36:09] [Server thread/INFO]: Sapling Growth Modifier: 100%
[08:36:09] [Server thread/INFO]: Beetroot Growth Modifier: 100%
[08:36:09] [Server thread/INFO]: Carrot Growth Modifier: 100%
[08:36:09] [Server thread/INFO]: Potato Growth Modifier: 100%
[08:36:09] [Server thread/INFO]: Wheat Growth Modifier: 100%
[08:36:09] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[08:36:09] [Server thread/INFO]: Vine Growth Modifier: 100%
[08:36:09] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[08:36:09] [Server thread/INFO]: Bamboo Growth Modifier: 100%
[08:36:09] [Server thread/INFO]: SweetBerry Growth Modifier: 100%
[08:36:09] [Server thread/INFO]: Kelp Growth Modifier: 100%
[08:36:09] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true
[08:36:09] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[08:36:09] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Bastion: 30084232 Fortress: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[08:36:09] [Server thread/INFO]: Max TNT Explosions: 100
[08:36:09] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[08:36:09] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[08:36:09] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[08:36:09] [Server thread/INFO]: Item Merge Radius: 2.5
[08:36:09] [Server thread/INFO]: Item Despawn Rate: 6000
[08:36:09] [Server thread/INFO]: View Distance: 10
[08:36:09] [Server thread/INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[08:36:09] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[08:36:09] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[08:36:09] [Server thread/INFO]: Mob Spawn Range: 8
[08:36:09] [Server thread/INFO]: [VarLight] Enabling in World [DXL_Game_6]
[08:36:09] [Server thread/INFO]: [INFO][TeleCraft] Checking StrangeBlocks for world : DXL_Game_6
[08:36:09] [Server thread/INFO]: [INFO][TeleCraft] finish to check StrangeBlocks : 0 OK | 0 FIXED | 0 REMOVED | 0 CLEANED
[08:36:09] [Server thread/INFO]: [CrazyCrates] Fixed 0 broken crate locations.
[08:36:09] [Server thread/INFO]: [WorldGuard] (DXL_Game_6) TNT ignition is PERMITTED.
[08:36:09] [Server thread/INFO]: [WorldGuard] (DXL_Game_6) Lighters are PERMITTED.
[08:36:09] [Server thread/INFO]: [WorldGuard] (DXL_Game_6) Lava fire is PERMITTED.
[08:36:09] [Server thread/INFO]: [WorldGuard] (DXL_Game_6) Fire spread is UNRESTRICTED.
[08:36:09] [Server thread/INFO]: [WorldGuard] Loaded configuration for world 'DXL_Game_6'
[08:36:09] [Server thread/INFO]: [dynmap] World 'DXL_Game_6' disabled
[08:36:09] [Server thread/INFO]: [dynmap] Full/radius render pause set to true
[08:36:09] [Server thread/INFO]: [dynmap] Update render pause set to true
[08:36:09] [Server thread/INFO]: Full/Radius renders are PAUSED
[08:36:09] [Server thread/INFO]: Update renders are PAUSED
[08:36:09] [Server thread/INFO]: Zoom out processing is ACTIVE
[08:36:09] [Server thread/INFO]: Refreshing configuration for world DXL_Game_6
[08:36:09] [Server thread/INFO]: [dynmap] World 'DXL_Game_6' disabled
[08:36:09] [Server thread/INFO]: If you are done editing map data, run '/dynmap pause none' to resume rendering
[08:36:09] [Server thread/INFO]: [dynmap] Full/radius render pause set to false
[08:36:09] [Server thread/INFO]: [dynmap] Update render pause set to false
[08:36:09] [Server thread/INFO]: Full/Radius renders are ACTIVE
[08:36:09] [Server thread/INFO]: Update renders are ACTIVE
[08:36:09] [Server thread/INFO]: Zoom out processing is ACTIVE
[08:36:09] [Craft Scheduler Thread - 652/INFO]: [EternalNature] Loaded 0 waterfalls

```

**Comment by Sataniel98** [comment] 2020-09-08 13:57
Thank you for the report. This is a duplicate of #805 and #828 though.

**Closed as completed by Sataniel98** 2020-09-08 13:57 UTC
Labels: DUPLICATE
