### ISSUE TITLE
trigger signal not working properly with redstone trigger

### ISSUE THREAD

**Issue by drAkeEngine** [DRE2N/DungeonsXL#976] opened 2021-02-13 10:15 UTC
**Description**
When using the trigger signs and these are activated with redstone when removing the signal it does not return to its original state, a redstone signal has to be sent again to deactivate the trigger

**Reproduce**

1- a dungeon was created with a trigger that when receiving redstone changes a block from stone to cobblestone, but when removing the redstone signal it does not return to being stone

**Expected behavior**

As you can see in the video, the block sign works perfectly when putting and removing the redstone signal.

but the trigger sign stays in the same state until another redstone signal is applied again, I remember that a long time ago this worked the same way, I don't know if this is an error or change this sign

**Screenshots / GIFs / videos**

https://www.dropbox.com/s/rlzblt18izbv1l9/signs.mp4

I use Paper-1.16.4-416
dungeonsxl-dist-0.18-SNAPSHOT-1070

Sorry for my bad english.

**Comment by Sataniel98** [comment] 2021-02-13 18:34
Looks like a duplicate of #841. I didn't forget this.

**Closed as completed by Sataniel98** 2021-02-13 18:34 UTC
Labels: DUPLICATE

**Comment by drAkeEngine** [comment] 2021-02-14 00:40
Thank you very much, it's just that a little time has passed, I thought you had forgotten about this.

I hope I have not caused any inconvenience, good morning and I hope it is not too difficult to solve this.

**Comment by drAkeEngine** [comment] 2021-02-14 00:41
> Looks like a duplicate of #841. I didn't forget this.

Thank you very much, it's just that a little time has passed, I thought you had forgotten about this.

I hope I have not caused any inconvenience, good morning and I hope it is not too difficult to solve this.
