### ISSUE TITLE
The command /dxl msg doesn't work

### ISSUE THREAD

**Issue by Tiplish** [DRE2N/DungeonsXL#164] opened 2016-09-30 17:17 UTC
Hello, 

When i try to perform the command /dxl msg 1 "blabla" it's say that an internal error occurred.

And i didn't find any help to edit message in the config file. Maybe i miss it.

Thx for help.

**Comment by Sataniel98** [comment] 2016-09-30 18:11
Duplicate of #144 unless it occurred with the latest dev build.

**Closed as completed by Sataniel98** 2016-09-30 18:11 UTC
Labels: DUPLICATE
