### ISSUE TITLE
Mythicmobs Error

### ISSUE THREAD

**Issue by LemonSolar** [DRE2N/DungeonsXL#674] opened 2019-10-06 04:51 UTC
HI, I tried to set these texts with 5 signs in my dungeon:

> [Mob]
> M1-1
> 1,1,MM

And i expect to set 5 mobs totally will be spawned when i played
However , 10+ mobs were spawned, anyone know why?
Also, i set this with in the dungeon:

> [End]
> 
> 
> > M M1-5

However, after i killed the mythicmobs "M1-5", the dungon doesn't end. So how can i set a dungeon will be ended after I killed a mythicmobs' mob?

These above problems have let me get into a trouble with a very long period of time. Please help!

**Comment by Sataniel98** [comment] 2019-10-12 13:11
Perhaps a duplicate of #475. MythicMobs mobs are used just like normal mobs in triggers. I can't tell why this doesn't work in your case.

**Closed as completed** 2019-11-06 16:44 UTC
Labels: DUPLICATE
