### ISSUE TITLE
Errors in console when renaming a Dungeon

### ISSUE THREAD

**Issue by trevor1097** [DRE2N/DungeonsXL#787] opened 2020-05-04 05:29 UTC
**Description**
Renaming a single floor dungeon throws errors in console

**Reproduce**
Rename a dungeon

**Expected behavior**
No errors in console on rename

```
[01:21:49] [Server thread/INFO]: trevor1097 issued server command: /dxl rename Test Sewer
[01:21:49] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'dxl' in plugin DungeonsXL v0.18-SNAPSHOT-958
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.15.2.jar:git-Paper-235]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-235]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:760) ~[patched_1.15.2.jar:git-Paper-235]
	at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1844) ~[patched_1.15.2.jar:git-Paper-235]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1652) ~[patched_1.15.2.jar:git-Paper-235]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Paper-235]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Paper-235]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-235]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-235]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-235]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-235]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-235]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1081) ~[patched_1.15.2.jar:git-Paper-235]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1074) ~[patched_1.15.2.jar:git-Paper-235]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.15.2.jar:git-Paper-235]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1208) ~[patched_1.15.2.jar:git-Paper-235]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:946) ~[patched_1.15.2.jar:git-Paper-235]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
Caused by: java.lang.IllegalStateException: Tried to access the dungeon config of a single floor dungeon
	at de.erethon.dungeonsxl.dungeon.DDungeon.getConfig(DDungeon.java:71) ~[?:?]
	at de.erethon.dungeonsxl.command.RenameCommand.onExecute(RenameCommand.java:69) ~[?:?]
	at de.erethon.commons.command.DRECommandExecutor.onCommand(DRECommandExecutor.java:67) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.15.2.jar:git-Paper-235]
	... 17 more
```

**Comment by Sataniel98** [comment] 2020-05-04 10:09
Duplicate of #752

**Closed as completed by Sataniel98** 2020-05-04 10:09 UTC
Labels: DUPLICATE
