### ISSUE TITLE
DPlayerJoinDGroupEvent.getDPlayer() glitch

### ISSUE THREAD

**Issue by mkcoldwolf** [DRE2N/DungeonsXL#661] opened 2019-09-20 15:18 UTC
**Description**
In DPlayerJoinDGroupEvent
both method 
- event.getDGroup.getCaptain();
- event.getDPlayer();
kinda glitched
for #getCaptain(); , it return null when player creating the group, i can understand this sinces the group object may not be exist before this event
for #getDPlayer(); , it always return null when player join a dgroup, but its fine when player creating a group, this is a serious glitch and has to be fixed

**Reproduce**
Code:
![image](https://user-images.githubusercontent.com/32544898/65338346-920bd000-dbfc-11e9-915b-16a41acfdedd.png)
Result:
![image](https://user-images.githubusercontent.com/32544898/65338327-86200e00-dbfc-11e9-9631-377a9d47b106.png)

**Expected behavior**
#getDPlayer(); should return the player who is join the group when this event fire

**Screenshots / GIFs / videos**
as in //Reproduce

**Relevant configuration files**
N.A.

**Comment by RogerPlaysMC** [comment] 2019-09-26 16:21
Yes, it is not functioning as intended. The DPlayer object is created when they either join a group or enter a dungeon. Since it’s not created yet when this event fires it is bound to return null. 

Might make more sense in this case to return DGlobalPlayer.

**Comment by Sataniel98** [comment] 2020-03-26 16:37
Sorry for the late reply! The events will be replaced with alternatives in the API module soon. This will be fixed on that occasion.

**Closed as completed** 2020-04-25 19:52 UTC
Labels: BUG

**Comment by Sataniel98** [comment] 2020-04-25 19:54
The new event API is finished now, but I've made a simple plugin that prints every fired DXL event to the chat. Minor changes might still be done when I've done some testing with it.
