### ISSUE TITLE
New Errors

### ISSUE THREAD

**Issue by apc274003** [DRE2N/DungeonsXL#751] opened 2020-04-07 05:31 UTC
Currently on the dev build #887 , trying it out, when I right click the ready sign in the dungeon, nothing happens and this is the error that pops up.
https://gyazo.com/17365e2580098678f604f56d0173cdc6

When you take damage in a dungeon
https://gyazo.com/7a909cfa573501ec8d5e0804124f5584

When you die in a dungeon
https://gyazo.com/3f1cef48dfdc42c429ac9d18e40ddf32

**Comment by Sataniel98** [comment] 2020-04-07 09:46
The first error will be fixed asap, the second is caused by the first and the last error is because the Quests module isn't updated for the build.

**Comment by apc274003** [comment] 2020-04-07 19:44
Okay let me know when it's fixed, and I'll test it again, also


I tried making a mob sign like this
[mob]
SkeletonKing
1,1,MM
D 3

The sign kept spawning SkeletonKings not just 1? Is the mob sign format different in this build?

**Comment by Sataniel98** [comment] 2020-04-08 09:08
The mob sign is a windup sign, it spawns its mobs again if it is triggered for a second time: https://github.com/DRE2N/DungeonsXL/wiki/New-sign-system-(v0.18)

The actual problem is that there are button, rocker and windup signs that need to be triggered once when someone is in distance (mob, door), those that need to be triggered multiple times whenever a player is close to them (checkpoint, message) and some signs where both kinds of behavior make sense (command, trigger).

Consistent behavior isn't possible with one distance trigger, so there will be one that removes itself after it is triggered and one that does not.

Build 893 changes the D trigger sothat it works like the first, because I believe users would rather have their mob signs work as they are than their checkpoints.

**Closed as completed** 2020-04-09 19:57 UTC
Labels: BUG
